#!/usr/bin/env perl

use strict;
use warnings;
use OPTiMaDe::FilterParser;
use Data::Dumper;

$Data::Dumper::Sortkeys = 1;

@ARGV = ( '-' ) unless @ARGV;

for (@ARGV) {
    my $parser = new OPTiMaDe::FilterParser;
    print Dumper( $parser->Run( $_ ) );
}
